- name: Ensure python3-pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install required Python libraries
  ansible.builtin.pip:
    name:
      - cryptography
      - PyMySQL
      - boto3
      - botocore
    executable: pip3

- name: Install MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: installed

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: connect to mysql server
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ lookup('amazon.aws.aws_ssm', '/expense/mysql/mysql_root_password', decrypt=True ) }}"
    login_host: "{{ mysql_host }}"
  register: mysql_info
  ignore_errors: true

- name: print the output
  ansible.builtin.debug:
    msg: "MySQL info: {{ mysql_info }}"

- debug:
    var: mysql_info.users
- name: Ensure root password is set
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ lookup('amazon.aws.aws_ssm', '/expense/mysql/mysql_root_password', decrypt=True) }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    check_implicit_admin: yes
    state: present

- name: Debug MySQL variables
  debug:
    msg:
      user: "{{ MYSQL_USER }}"
      host: "{{ MYSQL_HOST }}"

